"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "vi" | "en";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, placeholders?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
    undefined,
);

// Translation dictionaries
const translations = {
    vi: {
        // Navigation
        "confirm.deleteAttachment": "Bạn có chắc chắn muốn xóa tập tin này?",
        "nav.leads": "Chăm khách",
        "nav.deals": "Chốt khách",
        "nav.customers": "Khách hàng",
        "nav.settings": "Cài đặt",
        "nav.organization": "Tổ chức",
        "nav.expansion": "Mở rộng",
        "nav.search": "Tìm kiếm",
        "nav.searchOrg": "Tìm kiếm tổ chức",
        "nav.createOrg": "Tạo tổ chức mới",
        "nav.reminders": "Nhắc nhở",

        // Error Messages
        "error.noActivity": "Chưa có hoạt động nào",
        "error.loadTimeline": "Lỗi tải timeline",

        // Common Actions
        "common.resetSidebarMenuSuccess": "Đặt lại menu về mặc định thành công",
        "common.resetSidebarMenuFailed": "Lỗi đặt lại menu về mặc định",
        "common.updateSidebarMenuSuccess": "Cập nhật menu thành công",
        "common.updateSidebarMenuFailed": "Lỗi cập nhật menu",
        "common.confirmReset":
            "Bạn có chắc chắn muốn đặt lại menu về mặc định? Tất cả các thay đổi sẽ bị mất.",
        "common.confirmResetDescription":
            "Bạn có chắc chắn muốn đặt lại menu về mặc định? Tất cả các thay đổi sẽ bị mất.",
        "common.reset": "Khôi phục mặc định",
        "common.resetting": "Đang khôi phục mặc định...",
        "common.week": "Tuần",
        "common.updateLabel": "Cập nhật nhãn",
        "common.createLabel": "Tạo nhãn",
        "common.hashtagList": "Danh sách hashtag",
        "common.hashtag": "Hashtag",
        "common.labelList": "Danh sách nhãn",
        "common.color": "Màu",
        "common.page": "Trang",
        "common.selectPage": "Chọn trang",
        "common.publishMode": "Chế độ xuất bản",
        "common.publishNow": "Xuất bản ngay",
        "common.schedulePublish": "Xuất bản lên lịch",
        "common.publishedTime": "Thời gian xuất bản",
        "common.writeSomething":
            "Viết gì đó hoặc sử dụng shortcodes, spintax, @ để nhắc đến...",
        "common.clickOrDragDropMedia": "Kéo và thả media hoặc nhấp để chọn",
        "common.labels": "Nhãn",
        "common.selectLabels": "Chọn nhãn",
        "common.hashtags": "Hashtag",
        "common.selectHashtags": "Chọn hashtag",
        "common.draft": "Bản nháp",
        "common.update": "Cập nhật",
        "common.schedule": "Lên lịch",
        "common.selectDateTime": "Chọn ngày và giờ xuất bản",
        "common.selectCampaign": "Chọn chiến dịch",
        "common.posts": "Bài viết",
        "common.deleteLead": "Xóa cơ hội",
        "common.noResults": "Không có kết quả",
        "common.extend": "Mở rộng",
        "common.manage": "Quản lý",
        "common.customerType": "Loại khách hàng",
        "common.utmSource": "Nguồn",
        "common.enterDealValue": "Nhập giá trị giao dịch",
        "common.justNow": "Vừa xong",
        "common.invalidDate": "Ngày không hợp lệ",
        "common.year": "năm",
        "common.yearAgo": "năm trước",
        "common.month": "tháng",
        "common.monthAgo": "tháng trước",
        "common.day": "ngày",
        "common.dayAgo": "ngày trước",
        "common.hour": "giờ",
        "common.hourAgo": "giờ trước",
        "common.minute": "phút",
        "common.minuteAgo": "phút trước",
        "common.customer": "Khách hàng",
        "common.customerName": "Tên khách hàng",
        "common.enterCustomerName": "Nhập tên khách hàng",
        "common.unknown": "Không xác định",
        "common.deleteLink": "Xóa liên kết",
        "common.enterWork": "Nhập nghề nghiệp",
        "common.enterPhysicalId": "Nhập CCCD",
        "common.work": "Nghề nghiệp",
        "common.physicalId": "CCCD",
        "common.enterAddress": "Nhập địa chỉ",
        "common.enterNote": "Nhập ghi chú",
        "common.confirmDeleteNoteDescription":
            "Bạn có chắc chắn muốn xóa ghi chú này?",
        "common.customerDetail": "Chi tiết khách hàng",
        "common.confirmDelete": "Xác nhận xóa",
        "common.confirmDeleteDescription":
            "Bạn có chắc chắn muốn xóa khách hàng này?",
        "common.convertToDeal": "Chuyển sang chốt khách",
        "common.close": "Đóng",
        "common.unassigned": "Chưa được gán",
        "common.error": "Có lỗi xảy ra",
        "common.follower": "Người theo dõi",
        "common.detail": "Chi tiết",
        "common.noFollowers": "Chưa có người theo dõi",
        "common.noAssignee": "Chưa có người phụ trách",
        "common.selectFollowers": "Chọn người theo dõi",
        "common.classification": "Phân loại",
        "common.selectCustomerToViewTimeline": "Chọn khách hàng để xem lịch sử",
        "common.selectCustomerToViewDetail": "Chọn khách hàng để xem chi tiết",
        "common.noActivity": "Chưa có hoạt động nào",
        "common.reminderDescription":
            "Nhắc hẹn về cuộc gọi, gặp gỡ, nhắc nhở, video, sự kiện sẽ xuất hiện tại đây",
        "common.collapse": "Thu gọn",
        "common.showMore": "Xem thêm",
        "common.reminders": "nhắc nhở",
        "common.deleteReminder": "Xóa nhắc nhở",
        "common.deleteReminderDescription":
            "Bạn có chắc chắn muốn xóa nhắc nhở này? Hành động này không thể hoàn tác.",
        "common.tag": "Nhãn",
        "common.import": "Nhập dữ liệu",
        "common.export": "Xuất dữ liệu",
        "common.refresh": "Làm mới",
        "common.history": "Lịch sử",
        "common.editNote": "Sửa ghi chú",
        "common.deleteNote": "Xóa ghi chú",
        "common.activity": "Hoạt động",
        "common.addActivity": "Thêm hoạt động",
        "common.note": "Ghi chú",
        "common.notes": "Ghi chú",
        "common.attachments": "Tập tin đính kèm",
        "common.conversation": "Cuộc hội thoại",
        "common.attachmentUpload": "Tải tệp",
        "common.attachmentUploadDescription":
            "Nhấp vào đây hoặc thả tập tin vào đây",
        "common.attachment": "Tập tin đính kèm",
        "common.deleteAttachment": "Xóa tập tin",
        "common.joinOrg": "Tham gia tổ chức",
        "common.company": "Công ty",
        "common.selectGender": "Chọn giới tính",
        "common.personal": "Cá nhân",
        "common.orgInfo": "Thông tin tổ chức",
        "common.personalProfile": "Thông tin cá nhân",
        "common.gender": "Giới tính",
        "common.enterGender": "Nhập giới tính",
        "common.male": "Nam",
        "common.female": "Nữ",
        "common.dob": "Ngày sinh",
        "common.enterDob": "Nhập ngày sinh",
        "common.address": "Địa chỉ",
        "common.about": "Giới thiệu",
        "common.enterAbout": "Nhập giới thiệu",
        "common.teams": "Đội sale",
        "common.noWorkspace": "Không có không gian làm việc",
        "common.leavedOrg": "Đã rời tổ chức",
        "common.leavedWorkspace": "Đã rời không gian",
        "common.leavedOrgError": "Có lỗi xảy ra khi rời tổ chức",
        "common.leavedWorkspaceError": "Có lỗi xảy ra khi rời không gian",
        "common.leaveOrganization": "Rời tổ chức",
        "common.leaveWorkspace": "Rời không gian",
        "common.fullName": "Họ và tên",
        "common.enterFullName": "Nhập họ và tên",
        "common.email": "Email",
        "common.enterEmail": "Nhập email",
        "common.phone": "Số điện thoại",
        "common.enterPhone": "Nhập số điện thoại",
        "common.position": "Chức vụ",
        "common.owner": "Chủ tổ chức",
        "common.admin": "Quản trị viên",
        "common.member": "Thành viên",
        "common.personalInfo": "Thông tin cá nhân",
        "common.organizationInfo": "Thông tin tổ chức",
        "common.members": "Thành viên",
        "common.save": "Lưu",
        "common.saving": "Đang lưu...",
        "common.cancel": "Hủy",
        "common.search": "Tìm kiếm",
        "common.add": "Thêm",
        "common.edit": "Chỉnh sửa",
        "common.delete": "Xóa",
        "common.send": "Gửi",
        "common.loading": "Đang tải...",
        "common.loadError": "Có lỗi xảy ra khi tải dữ liệu",
        "common.tryOtherKeywords": "Thử tìm kiếm với từ khóa khác",
        "common.source": "Nguồn",
        "common.description": "Mô tả",
        "common.default": "Mặc định",
        "common.workspaces": "Không gian làm việc",
        "common.report": "Báo cáo",
        "common.products": "Sản phẩm",
        "common.archive": "Lưu trữ",
        "common.restore": "Khôi phục",
        "common.customerCareOpportunities": "Cơ hội chăm khách",
        "common.allCustomers": "Tất cả khách hàng",
        "common.deleteCustomer": "Xóa khách hàng",
        "common.name": "Tên",
        "common.productCode": "Mã sản phẩm",
        "common.tax": "Thuế",
        "common.category": "Danh mục",
        "common.selectCategory": "Chọn danh mục",
        "common.image": "Ảnh",
        "common.selectImage": "Chọn ảnh",
        "common.images": "Ảnh",
        "common.selectImages": "Chọn ảnh",
        "common.searchCustomer": "Tìm kiếm khách hàng...",
        "common.mailBox": "Hộp thư",
        // Member Management
        "member.management": "Quản lý thành viên",
        "member.information": "Thông tin thành viên",
        "member.email": "Email",
        "member.phone": "Số điện thoại",
        "member.address": "Địa chỉ",
        "member.position": "Chức vụ",
        "member.joinDate": "Ngày tham gia",
        "member.notUpdated": "Chưa cập nhật",
        "member.assignResources": "Gán tài nguyên",
        "member.removeFromOrg": "Xóa khỏi tổ chức",
        "member.add": "Thêm thành viên",
        "member.search": "Tìm kiếm thành viên",
        "member.searchPlaceholder": "Tìm kiếm thành viên...",
        "member.noMembers": "Chưa có thành viên nào",
        "member.notFound": "Không tìm thấy thành viên nào",
        "member.selectToView": "Chọn một thành viên để xem thông tin chi tiết",
        "member.count": "thành viên",
        "member.searchEmail": "Tìm kiếm email thành viên...",
        "member.inviteSent": "Đã gửi lời mời",
        "member.inviteFailed": "Gửi lời mời thất bại",
        "member.inactive": "Không hoạt động",
        "member.invite": "Mời",
        "member.invited": "Đã mời",
        "member.assigningTo": "Đang gán quyền cho",

        // Permission Groups
        "permission.removeFromGroupConfirm":
            "Bạn có chắc chắn muốn xóa thành viên này khỏi nhóm?",
        "permission.removeFromGroupDescription":
            "Bạn có chắc chắn muốn xóa {name} khỏi nhóm {groupName}?",
        "permission.removeFromGroup": "Xóa khỏi nhóm",
        "permission.noPermission": "Không có quyền",
        "permission.group": "Nhóm quyền",
        "permission.search": "Tìm kiếm nhóm quyền",
        "permission.searchPlaceholder": "Tìm kiếm nhóm quyền...",
        "permission.selectToView": "Chọn một nhóm quyền để xem thông tin",
        "permission.cancelEdit": "Hủy chỉnh sửa",
        "permission.addNew": "Thêm nhóm quyền mới",
        "permission.organization": "Tổ chức",
        "permission.workspace": "Không gian làm việc",
        "permission.noOrgGroups": "Chưa có nhóm quyền tổ chức",
        "permission.noWorkspaceGroups":
            "Chưa có nhóm quyền không gian làm việc",
        "permission.default": "Mặc định",
        "permission.noResults": "Không tìm thấy kết quả",
        "permission.noGroups": "Chưa có nhóm quyền",
        "permission.createFirst": "Tạo nhóm quyền đầu tiên của bạn",
        "permission.name": "Tên nhóm quyền",
        "permission.grantPermission": "Cấp quyền",
        "permission.noPermissions": "Chưa có quyền",
        "permission.noPermissionsDescription":
            "Nhóm quyền này chưa được cấp quyền nào.",
        "permission.granted": "được cấp",
        "permission.permission": "quyền",
        "permission.notGranted": "chưa được cấp",
        "permission.workspacePermission": "Quyền workspace",
        "permission.workspaceRole": "Vai trò trong workspace",
        "permission.grantSuccess": "Cấp quyền thành công",
        "permission.granting": "Đang cấp quyền...",
        "permission.nameRequired": "Tên nhóm quyền không được để trống",
        "permission.enterName": "Nhập tên nhóm quyền",
        "permission.enterDescription": "Nhập mô tả cho nhóm quyền",
        "permission.selectPermissions": "Chọn quyền",
        "permission.selectedCount": "Đã chọn {count} quyền",
        "permission.noPermissionsFound": "Không tìm thấy quyền nào",
        "permission.createSuccess": "Tạo nhóm quyền thành công",
        "permission.organizationPermission": "Quyền tổ chức",
        "permission.selectOrgPermission": "Chọn quyền tổ chức",
        "permission.permissions": "Quyền",
        "permission.noMembersAvailable": "Không có thành viên",
        "permission.noMembersDescription":
            "Chưa có thành viên nào có thể gán quyền này",
        "permission.hasPermission": "Đã có quyền",
        "permission.noPermissionStatus": "Chưa có quyền",
        "permission.assignPermission": "Gán quyền",
        "permission.assigning": "Đang gán...",
        "permission.assignSuccess": "Gán quyền cho thành viên thành công",
        "permission.assignError": "Có lỗi xảy ra khi gán quyền",
        "permission.workspaces": "Workspaces",
        "permission.noWorkspaces": "Không có workspace",
        "permission.noWorkspacesDescription": "Chưa có workspace nào được tạo",
        "permission.allWorkspaces": "Tất cả workspace",
        "permission.hasWorkspaceRole": "Có quyền",
        "permission.noWorkspaceRole": "Chưa có quyền",
        "permission.selectWorkspaceFirst":
            "Vui lòng chọn workspace để gán quyền",
        "permission.selectWorkspaceToViewMembers":
            "Chọn workspace để xem danh sách thành viên cụ thể",
        "permission.clickToViewMembers": "Click để xem thành viên",
        "permission.availableToAssign": "Có thể gán",
        "permission.allMembersHavePermission": "Tất cả thành viên đã có quyền",

        // Product
        "product.deals": "Giao dịch",
        "product.variations": "Biến thể",
        "product.prices": "Giá",
        "product.images": "Ảnh",
        "product.categories": "Danh mục",
        "product.description": "Mô tả",
        // Confirmations
        "confirm.updateOrgPermission.title": "Cập nhật quyền tổ chức",
        "confirm.updateOrgPermission.description":
            "Bạn có chắc chắn muốn cấp quyền '{permissionName}' cho {name}?",

        // Deals & Customers
        "deal.customers": "Khách hàng",
        "deal.allCustomers": "Tất cả khách hàng",
        "deal.sendDetails": "Gửi thông tin chi tiết",
        "deal.sendMail": "Gửi mail",
        "deal.saveNote": "Lưu ghi chú",
        "deal.emailSent": "Email đã được gửi đến khách hàng",
        "deal.totalRevenue": "Tổng doanh thu",
        "deal.pipeline": "Pipeline",
        "deal.list": "Danh sách",
        "deal.transactions": "Giao dịch",
        "deal.deleteStage": "Xóa stage",
        "deal.loadingMoreDeals": "Đang tải thêm giao dịch...",
        "deal.loaded": "Đã tải",
        "deal.loadMoreDeals": "Tải thêm giao dịch",
        "deal.dropDealsHere": "Kéo giao dịch vào đây",
        "deal.dragToArrangeStages": "Kéo để sắp xếp stage",
        "deal.clickToEditName": "Click để chỉnh sửa tên",
        "deal.deleteStageConfirm": "Xoá giai đoạn này?",
        "deal.currentDeals":
            "Hiện đang có: {count} giao dịch trong giai đoạn {stageName}",
        "deal.whatToDoWithDeals": "Bạn muốn làm gì với những giao dịch này?",
        "deal.moveToOtherStage": "Chuyển đến giai đoạn khác",
        "deal.selectStage": "Chọn giai đoạn",
        "deal.deleteDeals": "Xoá giao dịch",
        "deal.cancel": "Huỷ",
        "deal.delete": "Xoá",
        "deal.confirmDelete": "Bạn có chắc chắn muốn xoá giai đoạn này?",

        // Customer Timeline
        "customer.addedManually": "Khách hàng được thêm từ nhập thủ công",
        "customer.addedFromContacts": "Khách hàng được thêm từ danh bạ",
        "customer.rated": "Khách hàng được đánh giá",
        "customer.revisited": "Khách hàng đã truy cập lại",
        "customer.firstVisit": "Khách hàng lần đầu truy cập",
        "customer.registered": "Khách hàng đăng ký form",
        "customer.sentMessage": "gửi tin nhắn cho khách hàng",

        // Workspace
        "workspace.title": "Không gian làm việc",
        "workspace.noWorkspace":
            "Thành viên chưa được gán vào không gian làm việc nào.",
        "workspace.permissions": "Phân quyền không gian làm việc",
        "workspace.removeFromWorkspace": "Xóa khỏi không gian làm việc",
        "workspace.noOtherPermissions": "Không có quyền khác",
        "workspace.workspace": "Không gian làm việc",
        "workspace.selectToAssignRole": "Nhấn vào để chọn quyền đội sale",
        "workspace.noAvailableWorkspace": "Không có workspace khả dụng",
        "workspace.selectWorkspace": "Chọn không gian làm việc",
        "workspace.selectWorkspacePlaceholder":
            "Chọn một không gian làm việc...",
        "workspace.permissionRequired": "Vui lòng chọn quyền workspace",

        // Team
        "team.noTeams": "Không có đội sale",
        "team.updateRole": "Cập nhật vai trò",
        "team.removeFromTeam": "Xóa khỏi đội",
        "team.noOtherRoles": "Không có vai trò khác",
        "team.teams": "đội",
        "team.hasSubteams": "Có đội con",
        "team.subteam": "Đội con",
        "team.roleRequired": "Vui lòng chọn ít nhất một vai trò trong đội",
        "team.assignTeams": "Gán đội sales",

        // Roles
        "role.owner": "Chủ tổ chức",
        "role.admin": "Quản trị viên",
        "role.member": "Thành viên",
        "role.teamLeader": "Trưởng nhóm",
        "role.subLeader": "Phó nhóm",
        "role.selectRole": "Chọn vai trò",

        // Actions
        "action.cancel": "Hủy",
        "action.confirm": "Xác nhận",
        "action.processing": "Đang xử lý...",

        "common.callcenter": "Tổng đài",

        // Confirmations
        "confirm.removeFromOrg.title": "Xóa thành viên khỏi tổ chức",
        "confirm.removeFromOrg.description":
            "Bạn có chắc chắn muốn xóa {name} khỏi tổ chức?",
        "confirm.removeFromTeam.title": "Xóa thành viên khỏi đội",
        "confirm.removeFromTeam.description":
            "Bạn có chắc chắn muốn xóa {name} khỏi đội {teamName}?",
        "confirm.removeFromWorkspace.title":
            "Xóa thành viên khỏi không gian làm việc",
        "confirm.removeFromWorkspace.description":
            'Bạn có chắc chắn muốn xóa {name} khỏi không gian làm việc "{workspaceName}"?',

        // Success messages
        "success.updatedGroupName": "Đã cập nhật tên nhóm",
        "error.updatedGroupName": "Có lỗi xảy ra khi cập nhật tên nhóm",
        "success.removedFromGroup": "Đã xóa thành viên khỏi nhóm",
        "error.removedFromGroup": "Có lỗi xảy ra khi xóa thành viên khỏi nhóm",
        "success.removedFromOrg": "Đã xóa thành viên khỏi tổ chức",
        "success.removedFromTeam": "Đã xóa thành viên khỏi đội {teamName}",
        "success.removedFromWorkspace":
            "Đã xóa thành viên khỏi không gian làm việc",
        "success.grantedPermission": 'Đã cấp quyền "{permissionName}"',
        "success.updatedRole": 'Đã cập nhật vai trò thành "{roleName}"',
        "success.deleteAttachment": "Đã xóa tập tin",
        // Error messages
        "error.deleteAttachment": "Có lỗi xảy ra khi xóa tập tin",
        "error.removeMember": "Có lỗi xảy ra khi xóa thành viên",
        "error.removeFromTeam": "Có lỗi xảy ra khi xóa thành viên khỏi đội",
        "error.removeFromWorkspace":
            "Có lỗi xảy ra khi xóa thành viên khỏi không gian làm việc",
        "error.grantPermission": "Có lỗi xảy ra khi cấp quyền",
        "error.updateRole": "Có lỗi xảy ra khi cập nhật vai trò",
        "error.createCustomer": "Có lỗi xảy ra khi tạo khách hàng",
        "error.createCustomerDescription":
            "Vui lòng kiểm tra lại thông tin khách hàng",
        "success.createCustomer": "Tạo khách hàng thành công",
        "success.createCustomerDescription":
            "Khách hàng đã được tạo thành công",
        "success.noteCustomer": "Ghi chú khách hàng đã được lưu",
        "error.noteCustomer": "Có lỗi xảy ra khi lưu ghi chú khách hàng",
        "success.updateCustomerStage":
            "Cập nhật trạng thái khách hàng thành công",
        "error.updateCustomerStage":
            "Có lỗi xảy ra khi cập nhật trạng thái khách hàng",
        "success.updateStage": "Cập nhật giai đoạn thành công",
        "success.updateWorkspace": "Cập nhật không gian làm việc thành công",
        "error.updateWorkspace":
            "Có lỗi xảy ra khi cập nhật không gian làm việc",
        "error.updateStage": "Có lỗi xảy ra khi cập nhật giai đoạn",
        "error.cannotDeleteLastStage": "Không thể xóa stage cuối cùng!",
        "success.deleteStage": "Xóa giai đoạn thành công",
        "error.deleteStage": "Có lỗi xảy ra khi xóa giai đoạn",
        "success.archiveCustomer": "Khách hàng đã được lưu trữ",
        "error.archiveCustomer": "Có lỗi xảy ra khi lưu trữ khách hàng",
        "success.archiveRestoreCustomer": "Khách hàng đã được khôi phục",
        "error.archiveRestoreCustomer":
            "Có lỗi xảy ra khi khôi phục khách hàng",
        "common.noArchivedCustomers": "Chưa có khách hàng được lưu trữ",
        "common.archivedCustomers": "Khách hàng đã lưu trữ",
        "success.deleteCustomer": "Khách hàng đã được xóa",
        "error.deleteCustomer": "Có lỗi xảy ra khi xóa khách hàng",
        "common.createSuccess": "Tạo thành công",
        "common.createFailed": "Tạo thất bại",
        "common.updateSuccess": "Cập nhật thành công",
        "common.updateFailed": "Cập nhật thất bại",
        "common.previous": "Trước",
        "common.next": "Tiếp",
        "common.morePages": "Thêm trang",
        "common.price": "Giá",
        "common.unitPrice": "Đơn giá",
        "common.currency": "Đơn vị tiền tệ",
        "common.details": "Chi tiết",
        "common.uploading": "Đang tải lên...",
        "common.upload": "Tải lên",
        "common.maxFileSize": "Tối đa {size}",
        "common.deleteImage": "Xóa hình ảnh",
        "common.deleteImageDescription":
            "Bạn có chắc chắn muốn xóa hình ảnh này?",
        "common.confirm": "Xác nhận",
        "common.confirmDescription":
            "Bạn có chắc chắn muốn thực hiện hành động này?",
        "common.deleteImageSuccess": "Ảnh đã được xóa",
        "common.deleteImageFailed": "Ảnh đã được xóa",
        "common.uploadImageSuccess": "Ảnh đã được tải lên",
        "common.uploadImageFailed": "Ảnh đã được tải lên",
        "common.all": "Tất cả",
        "common.won": "Thành công",
        "common.lost": "Thất bại",
        "common.time": "Thời gian",
        "common.quantity": "Số lượng",
        "common.totalAmount": "Tổng tiền",
        "common.viewDetail": "Xem chi tiết",
        "common.productName": "Tên sản phẩm",
        "common.createdDate": "Ngày tạo",
        "common.actions": "Hành động",
        "common.status": "Trạng thái",
        "common.noImage": "Không có hình ảnh",
        "common.filter": "Bộ lọc",
        "common.columnConfig": "Hiển thị cột",
        "common.open": "Mới",
        "common.customerList": "Danh sách khách hàng",
        "common.organization": "Tổ chức",
        "common.summary": "Tổng quan",
        "common.leads": "Cơ hội",
        "common.deals": "Giao dịch",
        "common.noLeads": "Chưa có cơ hội",
        "common.noDeals": "Chưa có giao dịch",
        "common.selectConversation": "Chọn cuộc hội thoại để xem thông tin",
        "common.dealValue": "Giá trị giao dịch",
        "common.product": "Sản phẩm",
        "common.workspace": "Không gian làm việc",
        "common.template": "Template",
        "common.stage": "Giai đoạn",
        "common.selectStage": "Chọn giai đoạn",
        "common.selectProduct": "Chọn sản phẩm",
        "common.selectWorkspace": "Chọn không gian làm việc",
        "common.underDevelopment": "Trang này đang được phát triển",
        "common.weAreWorkingHardToFinishThisFeature":
            "Chúng tôi đang làm việc chăm chỉ để hoàn thành tính năng này. Vui lòng quay lại sau.",
        "common.pleaseCheckBackSoon": "Vui lòng quay lại sau.",
        // Business Process
        "businessProcess.createSuccess":
            "Giai đoạn kinh doanh đã được tạo thành công",
        "businessProcess.createError":
            "Có lỗi xảy ra khi tạo giai đoạn kinh doanh",
        "businessProcess.createTaskSuccess":
            "Task kinh doanh đã được tạo thành công",
        "businessProcess.createTaskError":
            "Có lỗi xảy ra khi tạo task kinh doanh",
        "businessProcess.createNoteSuccess": "Ghi chú đã được tạo thành công",
        "businessProcess.createNoteError": "Có lỗi xảy ra khi tạo ghi chú",
        "success.updateTaskStatus": "Cập nhật trạng thái thành công",
        "error.updateTaskStatus": "Có lỗi xảy ra khi cập nhật trạng thái",
        "success.createTag": "Tạo nhãn thành công",
        "error.createTag": "Có lỗi xảy ra khi tạo nhãn",
        "success.noteLead": "Ghi chú đã được lưu",
        "error.noteLead": "Có lỗi xảy ra khi lưu ghi chú",
        "success.editNote": "Ghi chú đã được cập nhật",
        "error.editNote": "Có lỗi xảy ra khi cập nhật ghi chú",
        "success.deleteNote": "Ghi chú đã được xóa",
        "error.deleteNote": "Có lỗi xảy ra khi xóa ghi chú",
        "common.uploadAttachmentSuccess": "Tập tin đã được tải lên",
        "common.uploadAttachmentFailed": "Có lỗi xảy ra khi tải lên tập tin",
        "success.createNote": "Ghi chú đã được tạo",
        "error.createNote": "Có lỗi xảy ra khi tạo ghi chú",
        "success.updateTags": "Cập nhật nhãn thành công",
        "error.updateTags": "Có lỗi xảy ra khi cập nhật nhãn",
        "success.updateAssignees": "Cập nhật người thực hiện thành công",
        "error.updateAssignees": "Có lỗi xảy ra khi cập nhật người thực hiện",
        "success.archieveTask": "Đã lưu trữ",
        "error.archieveTask": "Có lỗi xảy ra khi lưu trữ",
        "success.unarchieveTask": "Đã mở lại",
        "error.unarchieveTask": "Có lỗi xảy ra khi mở lại",
        "success.duplicateTask": "Đã nhân bản",
        "error.duplicateTask": "Có lỗi xảy ra khi nhân bản",
        "success.deleteTask": "Đã xóa",
        "error.deleteTask": "Có lỗi xảy ra khi xóa",
        "success.updateTask": "Cập nhật thành công",
        "error.updateTask": "Có lỗi xảy ra khi cập nhật",

        // Nav
        "nav.wallet": "Số dư ví",
        "nav.logout": "Đăng xuất",
        "nav.viewProfile": "Xem Profile của bạn",

        // Conversation
        "conversation.linkConversation": "Liên kết cuộc hội thoại",
        "conversation.linkConversationDescription":
            "Bạn có chắc chắn muốn liên kết cuộc hội thoại này?",
        "success.linkConversation": "Cuộc hội thoại đã được liên kết",
        "error.linkConversation": "Có lỗi xảy ra khi liên kết cuộc hội thoại",

        // Leads
        "lead.createLead": "Tạo mới cơ hội",
        "customer.createCustomer": "Tạo mới khách hàng",
        "success.assignLead": "Đã gán người phụ trách",
        "error.assignLead": "Có lỗi xảy ra khi gán người phụ trách",
        "success.updateLead": "Cập nhật thành công",
        "error.updateLead": "Có lỗi xảy ra khi cập nhật",
        "success.linkLeadSuccess": "Đã liên kết với lead",
        "error.linkLeadSuccess": "Có lỗi xảy ra khi liên kết với lead",
        "success.linkCustomerSuccess": "Đã liên kết với khách hàng",
        "error.linkCustomerSuccess":
            "Có lỗi xảy ra khi liên kết với khách hàng",
        "success.unlinkLeadSuccess": "Đã bỏ liên kết với lead",
        "error.unlinkLeadSuccess": "Có lỗi xảy ra khi bỏ liên kết với lead",
        "success.unlinkCustomerSuccess": "Đã bỏ liên kết với khách hàng",
        "error.unlinkCustomerSuccess":
            "Có lỗi xảy ra khi bỏ liên kết với khách hàng",
        "success.link": "Liên kết thành công",
        "error.link": "Có lỗi xảy ra khi liên kết",
        "success.unlink": "Đã bỏ liên kết",
        "error.unlink": "Có lỗi xảy ra khi bỏ liên kết",
        "nav.automation": "Automation",

        "success.update": "Cập nhật thành công",
        "error.update": "Có lỗi xảy ra khi cập nhật",
        "success.create": "Tạo thành công",
        "error.create": "Có lỗi xảy ra khi tạo",
        "success.delete": "Xóa thành công",
        "error.delete": "Có lỗi xảy ra khi xóa",
        "success.archive": "Lưu trữ thành công",
        "common.addNew": "Thêm mới",
        "config.title": "Cấu hình",
        "config.aichatbot": "AI Chatbot",
        "config.fbconnect": "Kết nối Facebook",
        "config.form": "Biểu mẫu",
        "config.zaloconnect": "Kết nối Zalo",
        "settings.myAccount": "Tài khoản của tôi",
        "wallet.title": "Ví COKA",
        "wallet.deposit": "Nạp tiền",
        "confirm.archive.title": "Xác nhận lưu trữ",
        "confirm.archive.description":
            "Bạn có chắc chắn muốn lưu trữ giao dịch này? Giao dịch sẽ được chuyển vào thư mục lưu trữ.",
        "confirm.unarchive.title": "Xác nhận khôi phục",
        "confirm.unarchive.description":
            "Bạn có chắc chắn muốn khôi phục giao dịch này từ thư mục lưu trữ?",
        "confirm.duplicate.title": "Xác nhận sao chép",
        "confirm.duplicate.description":
            "Bạn có chắc chắn muốn tạo bản sao của giao dịch này?",
        "confirm.delete.title": "Xác nhận xóa",
        "confirm.delete.description":
            "Bạn có chắc chắn muốn xóa giao dịch này? Hành động này không thể hoàn tác.",
        "confirm.unsavedChanges.title": "Xác nhận đóng",
        "confirm.unsavedChanges.description":
            "Bạn có thay đổi chưa được lưu. Bạn có chắc chắn muốn đóng mà không lưu?",
        "common.call": "Gọi tới {phone}",
        "common.settings": "Cài đặt",
        "common.connect": "Kết nối",
        "common.opportunity": "Cơ hội",
        "common.form": "Form",
        "common.aiChatbot": "AI Chatbot",
        "common.followers": "Người theo dõi",
        "common.noAssigner": "Chưa có người phụ trách",
        "common.assigner": "Người phụ trách",
        "common.cancelInvitation": "Hủy lời mời",
        "common.cancelRequest": "Hủy yêu cầu",
        "success.cancelInvitation": "Hủy lời mời thành công",
        "error.cancelInvitation": "Có lỗi xảy ra khi hủy lời mời",
        "success.cancelRequest": "Hủy yêu cầu thành công",
        "error.cancelRequest": "Có lỗi xảy ra khi hủy yêu cầu",
        "success.acceptInvitation": "Chấp nhận lời mời thành công",
        "error.acceptInvitation": "Có lỗi xảy ra khi chấp nhận lời mời",
        "success.acceptRequest": "Chấp nhận yêu cầu thành công",
        "error.acceptRequest": "Có lỗi xảy ra khi chấp nhận yêu cầu",
        "success.rejectInvitation": "Từ chối lời mời thành công",
        "error.rejectInvitation": "Có lỗi xảy ra khi từ chối lời mời",
        "success.rejectRequest": "Từ chối yêu cầu thành công",
        "error.rejectRequest": "Có lỗi xảy ra khi từ chối yêu cầu",
        "wallet.balance": "Số dư hiện có",
        "member.searchEmailOrName": "Tìm kiếm theo email hoặc tên",
        "success.createBusinessProcessTask": "Tạo giao dịch thành công",
        "error.createBusinessProcessTask": "Có lỗi xảy ra khi tạo giao dịch",
        "success.createWorkspace": "Tạo không gian làm việc thành công",
        "error.createWorkspace": "Có lỗi xảy ra khi tạo không gian làm việc",
        "deal.selectColor": "Chọn màu",
        "common.copied": "Đã sao chép",
        "common.notifications": "Thông báo",
        "common.selectOpportunityOrDeal":
            "Chọn một cơ hội/giao dịch có sẵn hoặc tạo cơ hội/giao dịch mới",
        "common.selectCustomer":
            "Chọn một khách hàng có sẵn hoặc tạo khách hàng mới",
        "common.chooseExistingOpportunity": "Thêm vào cơ hội có sẵn",
        "common.chooseExistingDeal": "Thêm vào giao dịch có sẵn",
        "common.createNewOpportunity": "Thêm cơ hội mới",
        "common.createNewDeal": "Thêm giao dịch mới",
        "common.createNewCustomer": "Thêm khách hàng mới",
        "common.enterAtLeast3Characters": "Nhập tối thiểu 3 ký tự để tìm kiếm",
        "common.noResult": "Không tìm thấy kết quả",
        "common.linking": "Đang liên kết...",
        "common.link": "Liên kết",
        "common.findDealOrTask": "Tìm Deal/Task",
        "common.findLead": "Tìm Lead",
        "common.select": "Chọn",
        "common.pleaseEnterCustomerNameOrSelectCompany":
            "Vui lòng nhập tên khách hàng hoặc chọn công ty",
        "common.noSelectCompany": "Không chọn công ty",
        "common.searchCompany": "Tìm kiếm công ty",
        "common.title": "Tiêu đề",
        "common.pleaseEnterTitle": "Vui lòng nhập tiêu đề",
        "common.enterTitle": "Điền tiêu đề",
        "common.pleaseEnterCustomerName": "Vui lòng nhập tên khách hàng",
        "common.assignee": "Người phụ trách",
        "common.selectTag": "Chọn nhãn",
        "common.creating": "Đang tạo...",
        "common.create": "Tạo mới",
        "common.selectCustomerType": "Chọn phân loại",
        "common.selectUtmSource": "Chọn nguồn",
        "common.searchUtmSource": "Tìm kiếm nguồn",
        "common.noSelect": "Không chọn",
        "common.selectAssignee": "Chọn người phụ trách",
        "common.mainContact": "Liên hệ chính",
        "common.mainEmail": "Email chính",
        "common.addProduct": "Thêm sản phẩm",
        "common.noProductFound": "Không tìm thấy sản phẩm",
        "common.enterProductName": "Nhập tên sản phẩm",
        "common.enterPrice": "Nhập giá",
        "common.enterQuantity": "Nhập số lượng",
        "common.enterTax": "Nhập thuế",
        "common.processing": "Đang xử lý...",
        "common.selected": "đã chọn",
        "common.enterMessage": "Nhập tin nhắn...",
        "common.uploadFile": "Tải lên file",
        "common.uploadImage": "Tải lên ảnh",
        "success.updateAvatar": "Cập nhật ảnh thành công",
        "error.updateAvatar": "Có lỗi xảy ra khi cập nhật ảnh",
        "common.upgradeAccount": "Nâng cấp tài khoản",
        "common.sidebarConfig": "Cấu hình sidebar",
        "common.packageService": "Gói dịch vụ",
        "common.noPackageFound": "Không tìm thấy gói dịch vụ",
        "common.currentPackage": "Gói thuê bao hiện tại",
        "common.currentPlan": "Gói hiện tại",
        "common.chooseExistingCustomer": "Chọn khách hàng có sẵn",
        "common.createDeal": "Tạo giao dịch mới",
        "success.deletedGroup": "Đã xóa nhóm",
        "error.deletedGroup": "Có lỗi xảy ra khi xóa nhóm",
        "common.deleteConfirm": "Bạn có chắc chắn muốn xóa nhóm quyền {name}?",
        "error.common": "Có lỗi xảy ra",
        "common.eventTransfer": "Sự kiện chuyển đổi",
        "success.deleteTag": "Xóa nhãn thành công",
        "error.deleteTag": "Có lỗi xảy ra khi xóa nhãn",
        "error.deleteWorkspace": "Có lỗi xảy ra khi xóa không gian làm việc",
        "success.deleteWorkspace": "Xóa không gian làm việc thành công",
        "common.exportSuccess": "Xuất file thành công",
        "common.exportError": "Có lỗi xảy ra khi xuất file",
        // Mail-box
        "mail.compose": "Soạn thư",
        "mail.inbox": "Hộp thư đến",
        "mail.sent": "Đã gửi",
        "mail.drafts": "Thư nháp",
        "mail.settings": "Thiết lập",
        "mail.folders": "Thư mục",
        "mail.labels": "Nhãn",
        "mail.noLabels": "Chưa có nhãn nào",
        "mail.search": "Tìm kiếm",
        "mail.selectAccount": "Chọn tài khoản",
        "mail.noAccount": "Không có tài khoản",
        "mail.noAccountMessage":
            "Chưa có tài khoản email nào. Vui lòng vào Thiết lập để cấu hình tài khoản email.",
        "mail.reply": "Trả lời",
        "mail.from": "Từ",
        "mail.to": "Đến",
        "mail.cc": "Cc",
        "mail.bcc": "Bcc",
        "mail.subject": "Tiêu đề",
        "mail.selectSender": "Chọn người gửi",
        "mail.templates": "Mẫu",
        "mail.insertField": "Chèn trường",
        "mail.writeWithAI": "Viết bằng AI",
        "mail.send": "Gửi",
        "mail.sending": "Đang gửi...",
        "mail.saveDraft": "Lưu nháp",
        "mail.savingDraft": "Đang lưu...",
        "mail.sendSuccess": "Gửi email thành công!",
        "mail.replySuccess": "Trả lời email thành công!",
        "mail.sendError": "Không thể gửi email",
        "mail.draftSaved": "Lưu nháp thành công!",
        "mail.delete": "Xóa",
        "mail.replyAll": "Trả lời tất cả",
        "mail.forward": "Chuyển tiếp",
        "mail.aiSummary": "Tóm tắt AI",
        "mail.addLabel": "Gắn nhãn",
        "mail.noEmailSelected": "Chưa có email nào được chọn",
        "mail.selectToRead": "Chọn email để đọc",
        "mail.loading": "Đang tải...",
        "mail.noEmails": "Chưa có email nào",
        "mail.loadMore": "Tải thêm",
        "mail.noResultsFound": "Không tìm thấy kết quả",
        "mail.validate.noRecipient": "Vui lòng nhập người nhận",
        "mail.validate.invalidEmail": "Email người nhận không hợp lệ",
        "mail.validate.invalidCc": "Email CC không hợp lệ",
        "mail.validate.invalidBcc": "Email BCC không hợp lệ",
        "mail.showMore": "Hiện thêm",
        "mail.showLess": "Ẩn bớt",
        "mail.actions": "Hành động",
        "mail.searchPlaceholder": "Tìm kiếm email...",
        "mail.selectAll": "Chọn tất cả",
        "mail.syncing": "Đang đồng bộ dữ liệu...",
        "mail.loadingMore": "Đang tải thêm...",
        "mail.toRecipient": "Tới",
        "mail.noRecipient": "(Không có người nhận)",
        "mail.conversationsSelected": "cuộc hội thoại đã chọn",
        "mail.bulkActionDescription":
            "Bạn có thể lưu trữ, xóa hoặc đánh dấu đã đọc cho các cuộc hội thoại này.",
        "mail.markAsRead": "Đánh dấu đã đọc",
        "mail.markAsUnread": "Đánh dấu chưa đọc",
        "mail.editDraft": "Chỉnh sửa nháp",
        "mail.deleteConfirm": "Xóa Email",
        "mail.deleteConfirmSingle":
            "Bạn có chắc chắn muốn chuyển email này vào thùng rác?",
        "mail.deleteConfirmBulk":
            "Bạn có chắc chắn muốn chuyển {count} cuộc hội thoại vào thùng rác?",
        "mail.deleteConfirmTitle": "Xóa email này?",
        "mail.deleteConfirmMessage":
            "Bạn có chắc chắn muốn xóa email này không? Hành động này không thể hoàn tác.",
        "mail.deleteSuccess": "Đã xóa email",
        "mail.deleteFailed": "Không thể xóa email",

        // Settings & Accounts
        "mail.settings.backToMailbox": "Quay lại hộp thư",
        "mail.settings.title": "Quản lý tài khoản Email",
        "mail.settings.description":
            "Thêm, sửa, xóa tài khoản email để kết nối với hệ thống",
        "mail.settings.addAccount": "Thêm tài khoản",
        "mail.settings.noAccounts": "Chưa có tài khoản email nào",
        "mail.settings.connectPrompt":
            "Kết nối tài khoản email của bạn để gửi và nhận email trực tiếp từ hệ thống.",
        "mail.account.displayName": "Tên hiển thị",
        "mail.account.displayNamePlaceholder":
            "VD: Email Công Ty (Nguyễn Văn A)",
        "mail.account.email": "Địa chỉ Email",
        "mail.account.emailPlaceholder": "email@example.com",
        "mail.account.username": "Tên người dùng",
        "mail.account.usernamePlaceholder": "Username đăng nhập",
        "mail.account.password": "Mật khẩu",
        "mail.account.passwordPlaceholder": "Mật khẩu ứng dụng/email",
        "mail.account.passwordHint": "Để trống nếu không muốn đổi mật khẩu",
        "mail.account.imapHost": "IMAP Host",
        "mail.account.imapPort": "Port",
        "mail.account.smtpServer": "SMTP Server",
        "mail.account.smtpPort": "SMTP Port",
        "mail.account.useSsl": "Sử dụng kết nối an toàn (SSL/TLS)",
        "mail.account.checkConnection": "Kiểm tra kết nối",
        "mail.account.saveSettings": "Lưu cài đặt",
        "mail.account.updateTitle": "Cập nhật tài khoản Email",
        "mail.account.addTitle": "Thêm tài khoản Email mới",
        "mail.account.imapPrompt": "Nhập thông tin máy chủ IMAP để kết nối",
        "mail.account.deleteConfirmTitle": "Xóa tài khoản email",
        "mail.account.deleteConfirmMessage":
            "Bạn có chắc chắn muốn xóa tài khoản email này không? Hành động này không thể hoàn tác.",
        "mail.account.connectionSuccess": "Kết nối thành công!",
        "mail.account.connectionFailed": "Kết nối thất bại",
        "mail.account.savedSuccess": "Đã lưu cài đặt tài khoản",
        "mail.account.deletedSuccess": "Đã xóa tài khoản",

        // Labels
        "mail.label.create": "Tạo nhãn mới",
        "mail.label.edit": "Chỉnh sửa nháp",
        "mail.label.name": "Tên nhãn",
        "mail.label.color": "Màu sắc",
        "mail.label.createButton": "Tạo nhãn",
        "mail.label.updateButton": "Cập nhật nhãn",
        "mail.label.deleteTitle": "Xóa nhãn",
        "mail.label.deleteConfirm": "Bạn có chắc chắn muốn xóa nhãn này không?",
        "mail.label.createSuccess": "Tạo nhãn thành công!",
        "mail.label.updateSuccess": "Đã cập nhật nhãn",
        "mail.label.deleteSuccess": "Đã xóa nhãn",

        // Filter
        "mail.filter": "Bộ lọc",
        "mail.filter.byDate": "Theo thời gian",
        "mail.filter.dateFrom": "Từ ngày",
        "mail.filter.dateTo": "Đến ngày",
        "mail.filter.status": "Trạng thái",
        "mail.filter.all": "Tất cả",
        "mail.filter.unread": "Chưa đọc",
        "mail.filter.read": "Đã đọc",
        "mail.filter.attachments": "Tệp đính kèm",
        "mail.filter.hasAttachments": "Có tệp đính kèm",
        "mail.filter.noAttachments": "Không có tệp",
        "mail.filter.classification": "Phân loại",
        "mail.filter.selected": "đã chọn",
        "mail.filter.selectLabel": "Chọn nhãn",
        "mail.filter.noLabelsFound": "Không tìm thấy nhãn",
        "mail.filter.searchSubject": "Tìm theo tiêu đề",
        "mail.filter.sortBy": "Sắp xếp theo",
        "mail.filter.dateReceived": "Ngày nhận",
        "mail.filter.newest": "Mới nhất",
        "mail.filter.oldest": "Cũ nhất",
        "mail.filter.clear": "Xóa bộ lọc",
        "mail.apply": "Áp dụng",

        // AI Summary
        "mail.aiSummaryTitle": "Tóm tắt bởi AI",
        "mail.analyzing": "Đang phân tích email...",
        "mail.pleaseWait": "Vui lòng đợi trong giây lát",
        "mail.summaryContent": "Nội dung tóm tắt",
        "mail.noSummaryData": "Không có dữ liệu tóm tắt",
        "mail.copiedToClipboard": "Đã sao chép vào clipboard",

        // Attachments
        "mail.dropFiles": "Thả file vào đây hoặc nhấp để tải lên",

        // Missing Forward Keys
        "mail.forwardTitle": "Chuyển tiếp Email",
        "mail.additionalMessage": "Tin nhắn bổ sung",
        "mail.addMessagePlaceholder": "Thêm tin nhắn của bạn...",
        "mail.includeAttachments": "Bao gồm tệp đính kèm",
        "mail.cancel": "Hủy",
        "mail.deleteSelected": "Xóa đã chọn",
        "mail.loadingDetail": "Đang tải chi tiết email...",
        "mail.noConversationSelected": "Chưa chọn cuộc hội thoại nào",
        "mail.selectConversationPrompt":
            "Chọn một cuộc hội thoại từ danh sách để xem chi tiết hoặc thực hiện hành động.",
        "mail.tooltip.editDraft": "Chỉnh sửa bản nháp",
        "mail.tooltip.reply": "Trả lời người gửi",
        "mail.tooltip.replyAll": "Trả lời tất cả",
        "mail.tooltip.forward": "Chuyển tiếp email này",
        "mail.edit": "Chỉnh sửa",
        "mail.attachment": "Tập tin đính kèm",
        "mail.attachments": "Tập tin đính kèm",
    },
    en: {
        // Navigation
        "common.callcenter": "Call center",
        "confirm.deleteAttachment":
            "Are you sure you want to delete this attachment?",
        "nav.leads": "Leads",
        "nav.deals": "Deals",
        "nav.customers": "Customers",
        "nav.settings": "Settings",
        "nav.organization": "Organization",
        "nav.expansion": "Expansion",
        "nav.search": "Search",
        "nav.searchOrg": "Search organization",
        "nav.createOrg": "Create new organization",
        "nav.reminders": "Reminders",
        // Error Messages
        "error.noActivity": "No activity",
        "error.loadTimeline": "Error loading timeline",
        // Common Actions
        "common.resetSidebarMenuSuccess":
            "Reset sidebar menu to default successfully",
        "common.resetSidebarMenuFailed": "Error resetting sidebar menu",
        "common.updateSidebarMenuSuccess": "Update sidebar menu successfully",
        "common.updateSidebarMenuFailed": "Error updating sidebar menu",
        "common.confirmReset":
            "Are you sure you want to reset the menu to default? All changes will be lost.",
        "common.reset": "Reset to default",
        "common.resetting": "Resetting to default...",
        "common.updateLabel": "Update label",
        "common.createLabel": "Create label",
        "common.week": "Week",
        "deal.selectColor": "Select color",
        "common.hashtagList": "Hashtag List",
        "common.hashtag": "Hashtag",
        "common.labelList": "Label List",
        "common.color": "Color",
        "common.page": "Page",
        "common.selectPage": "Select page",
        "common.publishMode": "Publish mode",
        "common.publishNow": "Publish now",
        "common.schedulePublish": "Schedule publish",
        "common.publishedTime": "Published time",
        "common.writeSomething":
            "Write something or use shortcodes, spintax, @ for mentioning...",
        "common.clickOrDragDropMedia": "Click or Drag & Drop media",
        "common.labels": "Labels",
        "common.selectLabels": "Select labels",
        "common.hashtags": "Hashtags",
        "common.selectHashtags": "Select hashtags",
        "common.draft": "Draft",
        "common.update": "Update",
        "common.schedule": "Schedule",
        "common.selectDateTime": "Select date and time",
        "common.selectCampaign": "Select campaign",
        "common.underDevelopment": "This page is under development",
        "common.weAreWorkingHardToFinishThisFeature":
            "We’re working hard to finish this feature. Please check back soon.",
        "common.posts": "Posts",
        "common.pleaseCheckBackSoon": "soon.",
        "common.noResults": "No results",
        "common.manage": "Manage",
        "common.justNow": "Just now",
        "common.invalidDate": "Invalid date",
        "common.year": "year",
        "common.yearAgo": "year ago",
        "common.month": "month",
        "common.monthAgo": "month ago",
        "common.day": "day",
        "common.dayAgo": "day ago",
        "common.hour": "hour",
        "common.hourAgo": "hour ago",
        "common.minute": "minute",
        "common.minuteAgo": "minute ago",
        "common.enterWork": "Enter work",
        "common.enterPhysicalId": "Enter physical id",
        "common.enterAddress": "Enter address",
        "common.unknown": "Unknown",
        "common.deleteLink": "Delete link",
        "common.work": "Work",
        "common.physicalId": "Physical id",
        "common.detail": "Detail",
        "common.customerDetail": "Customer Detail",
        "common.enterNote": "Enter note",
        "common.confirmDeleteNoteDescription":
            "Are you sure you want to delete this note?",
        "common.confirmDelete": "Confirm Delete",
        "common.confirmDeleteDescription":
            "Are you sure you want to delete this customer?",
        "common.convertToDeal": "Convert to Deal",
        "common.close": "Close",
        "common.unassigned": "Unassigned",
        "common.error": "An error occurred",
        "common.follower": "Follower",
        "common.classification": "Classification",
        "common.noFollowers": "No followers",
        "common.noAssignee": "No assignee",
        "common.selectFollowers": "Select followers",
        "common.selectCustomerToViewTimeline":
            "Select customer to view timeline",
        "common.selectCustomerToViewDetail": "Select customer to view detail",
        "common.noActivity": "No activity",
        "common.reminderDescription":
            "Reminders about calls, meetings, reminders, videos, events will appear here",
        "common.collapse": "Collapse",
        "common.showMore": "Show more",
        "common.reminders": "reminders",
        "common.addActivity": "Add activity",
        "common.deleteReminder": "Delete reminder",
        "common.deleteReminderDescription":
            "Are you sure you want to delete this reminder?",
        "common.import": "Import",
        "common.export": "Export",
        "common.refresh": "Refresh",
        "common.history": "History",
        "common.editNote": "Edit note",
        "common.deleteNote": "Delete note",
        "common.activity": "Activities",
        "common.note": "Note",
        "common.notes": "Notes",
        "common.attachments": "Attachments",
        "common.conversation": "Conversation",
        "common.attachmentUpload": "Upload attachment",
        "common.attachmentUploadDescription": "Click here or drop files here",
        "common.attachment": "Attachment",
        "common.deleteAttachment": "Delete attachment",
        "common.joinOrg": "Join organization",
        "common.company": "Company",
        "common.selectGender": "Select gender",
        "common.personal": "Personal",
        "common.organization": "Organization",
        "common.orgInfo": "Organization Info",
        "common.personalProfile": "Personal Profile",
        "common.gender": "Gender",
        "common.enterGender": "Enter gender",
        "common.male": "Male",
        "common.female": "Female",
        "common.dob": "Date of birth",
        "common.enterDob": "Enter date of birth",
        "common.address": "Address",
        "common.about": "About",
        "common.enterAbout": "Enter about",
        "common.teams": "Sales teams",
        "common.noWorkspace": "No workspace",
        "common.leavedOrg": "Leaved organization",
        "common.leavedWorkspace": "Leaved workspace",
        "common.leavedOrgError": "An error occurred while leaving organization",
        "common.leavedWorkspaceError":
            "An error occurred while leaving workspace",
        "common.personalInfo": "Personal Info",
        "common.leaveOrganization": "Leave Organization",
        "common.leaveWorkspace": "Leave Workspace",
        "common.fullName": "Full Name",
        "common.enterFullName": "Enter full name",
        "common.email": "Email",
        "common.enterEmail": "Enter email",
        "common.phone": "Phone Number",
        "common.enterPhone": "Enter phone number",
        "common.position": "Position",
        "common.owner": "Owner",
        "common.admin": "Administrator",
        "common.member": "Member",
        "common.save": "Save",
        "common.saving": "Saving...",
        "common.cancel": "Cancel",
        "common.search": "Search",
        "common.add": "Add",
        "common.edit": "Edit",
        "common.delete": "Delete",
        "common.send": "Send",
        "common.loading": "Loading...",
        "common.loadError": "An error occurred while loading data",
        "common.tryOtherKeywords": "Try searching with other keywords",
        "common.source": "Source",
        "common.description": "Description",
        "common.organizationInfo": "Organization Info",
        "common.members": "Members",
        "common.default": "Default",
        "common.workspaces": "Workspaces",
        "common.report": "Report",
        "common.products": "Products",
        "common.archive": "Archive",
        "common.restore": "Restore",
        "common.customerCareOpportunities": "Customer Care Opportunities",
        "common.allCustomers": "All customers",
        "common.deleteCustomer": "Delete customer",
        "common.createSuccess": "Create success",
        "common.createFailed": "Create failed",
        "common.updateSuccess": "Update success",
        "common.updateFailed": "Update failed",
        "common.previous": "Previous",
        "common.next": "Next",
        "common.morePages": "More pages",
        "common.price": "Price",
        "common.unitPrice": "Unit Price",
        "common.currency": "Currency",
        "common.details": "Details",
        "common.name": "Name",
        "common.productCode": "Product Code",
        "common.tax": "Tax",
        "common.category": "Category",
        "common.selectCategory": "Select category",
        "common.image": "Image",
        "common.images": "Images",
        "common.selectImage": "Select image",
        "common.selectImages": "Select images",
        "common.uploading": "Uploading...",
        "common.upload": "Upload",
        "common.maxFileSize": "Max file size: {size}",
        "common.deleteImage": "Delete image",
        "common.deleteImageDescription":
            "Are you sure you want to delete this image?",
        "common.confirm": "Confirm",
        "common.confirmDescription":
            "Are you sure you want to perform this action?",
        "common.deleteImageSuccess": "Image deleted successfully",
        "common.deleteImageFailed": "Image deleted failed",
        "common.uploadImageSuccess": "Image uploaded successfully",
        "common.uploadImageFailed": "Image uploaded failed",
        "common.all": "All",
        "common.won": "Won",
        "common.lost": "Lost",
        "common.time": "Time",
        "common.quantity": "Quantity",
        "common.totalAmount": "Total Amount",
        "common.customer": "Customer",
        "common.viewDetail": "View detail",
        "common.productName": "Product Name",
        "common.createdDate": "Created Date",
        "common.actions": "Actions",
        "common.status": "Status",
        "common.filter": "Filter",
        "common.columnConfig": "Column Config",
        "common.open": "Open",
        "common.customerList": "Customer List",
        "common.searchCustomer": "Search customer...",
        "common.summary": "Summary",
        "common.leads": "Leads",
        "common.deals": "Deals",
        "common.noLeads": "No leads yet",
        "common.noDeals": "No deals yet",
        "common.selectConversation": "Select conversation to view details",
        // Source Management
        "common.customerType": "Customer type",
        "common.utmSource": "Source",
        // Member Management
        "member.management": "Member Management",
        "member.information": "Member Information",
        "common.selectOpportunityOrDeal":
            "Choose an existing opportunity/deal or create a new one.",
        "common.selectCustomer":
            "Choose an existing customer or create a new one",
        "common.chooseExistingOpportunity": "Add existing opportunity",
        "common.chooseExistingDeal": "Add existing deal",
        "common.chooseExistingCustomer": "Add existing customer",
        "common.createNewOpportunity": "Create new opportunity",
        "common.createNewDeal": "Create new deal",
        "common.createNewCustomer": "Create new customer",
        "common.enterAtLeast3Characters":
            "Enter at least 3 characters to search",
        "common.noResult": "No result",
        "common.linking": "Linking...",
        "common.link": "Link",
        "common.findDealOrTask": "Find Deal/Task",
        "common.findLead": "Find Lead",
        "common.pleaseEnterCustomerNameOrSelectCompany":
            "Please enter customer name or select company",
        "common.noSelectCompany": "No select company",
        "common.searchCompany": "Search company",
        "common.title": "Title",
        "common.pleaseEnterTitle": "Please enter title",
        "common.enterTitle": "Enter title",
        "common.customerName": "Customer name",
        "common.pleaseEnterCustomerName": "Please enter customer name",
        "common.assignee": "Assignee",
        "common.tag": "Tag",
        "common.selectTag": "Select tag",
        "common.creating": "Creating...",
        "common.create": "Create",
        "common.selectCustomerType": "Select customer type",
        "common.selectUtmSource": "Select source",
        "common.searchUtmSource": "Search source",
        "common.noSelect": "No select",
        "common.selectAssignee": "Select assignee",
        "common.mainContact": "Main contact",
        "common.mainEmail": "Main email",
        "common.selectTemplate": "Select template",
        "common.stage": "Stage",
        "common.dealValue": "Deal value",
        "common.enterDealValue": "Enter deal value",
        "common.product": "Product",
        "common.selectProduct": "Select product",
        "common.workspace": "Workspace",
        "common.selectWorkspace": "Select workspace",
        "common.template": "Template",
        "common.selectStage": "Select stage",
        "common.addProduct": "Add product",
        "common.noProductFound": "No product found",
        "common.enterProductName": "Enter product name",
        "common.enterPrice": "Enter price",
        "common.enterQuantity": "Enter quantity",
        "common.enterTax": "Enter tax",
        "common.processing": "Processing...",
        "common.selected": "selected",
        "common.enterMessage": "Enter message...",
        "common.uploadFile": "Upload file",
        "common.uploadImage": "Upload image",
        "common.upgradeAccount": "Upgrade account",
        "common.sidebarConfig": "Sidebar configuration",
        "common.packageService": "Package Service",
        "common.noPackageFound": "No package found",
        "common.currentPackage": "Current Package",
        "common.currentPlan": "Current Plan",
        "common.createDeal": "Create new deal",
        "common.copied": "Copied",
        "success.deleteTag": "Delete tag successfully",
        "error.deleteTag": "Error deleting tag",
        // Member Management
        "member.email": "Email",
        "member.phone": "Phone Number",
        "member.address": "Address",
        "member.position": "Position",
        "member.joinDate": "Join Date",
        "member.notUpdated": "Not updated",
        "member.assignResources": "Assign Resources",
        "member.removeFromOrg": "Remove from Organization",
        "member.add": "Add Member",
        "member.search": "Search Members",
        "member.searchPlaceholder": "Search members...",
        "member.noMembers": "No members yet",
        "member.notFound": "No members found",
        "member.selectToView": "Select a member to view details",
        "member.count": "members",
        "member.searchEmail": "Search member email...",
        "member.inviteSent": "Invitation sent",
        "member.inviteFailed": "Failed to send invitation",
        "member.inactive": "Inactive",
        "member.invite": "Invite",
        "member.invited": "Invited",
        "member.assigningTo": "Assigning to",

        // Permission Groups
        "permission.removeFromGroupDescription":
            "Are you sure you want to remove {name} from the group {groupName}?",
        "permission.removeFromGroup": "Remove from group",
        "permission.removeFromGroupConfirm":
            "Are you sure you want to remove this member from the group?",
        "permission.group": "Permission Group",
        "permission.search": "Search Permission Groups",
        "permission.searchPlaceholder": "Search permission groups...",
        "permission.selectToView": "Select a permission group to view details",
        "permission.cancelEdit": "Cancel editing",
        "permission.addNew": "Add new permission group",
        "permission.organization": "Organization",
        "permission.workspace": "Workspaces",
        "permission.noOrgGroups": "No organization permission groups yet",
        "permission.noWorkspaceGroups": "No workspace permission groups yet",
        "permission.default": "Default",
        "permission.noResults": "No results found",
        "permission.noGroups": "No permission groups yet",
        "permission.createFirst": "Create your first permission group",
        "permission.name": "Permission Name",
        "permission.grantPermission": "Grant permission",
        "permission.noPermissions": "No permissions",
        "permission.noPermissionsDescription":
            "This permission group has no permissions yet.",
        "permission.granted": "granted",
        "permission.permission": "permission",
        "permission.notGranted": "not granted",
        "permission.workspacePermission": "Workspace permission",
        "permission.workspaceRole": "Workspace Role",
        "permission.grantSuccess": "Permissions granted successfully",
        "permission.granting": "Granting permissions...",
        "permission.nameRequired": "Permission group name is required",
        "permission.enterName": "Enter permission group name",
        "permission.enterDescription": "Enter permission group description",
        "permission.selectPermissions": "Select Permissions",
        "permission.selectedCount": "Selected {count} permissions",
        "permission.noPermissionsFound": "No permissions found",
        "permission.createSuccess": "Permission group created successfully",
        "permission.organizationPermission": "Organization Permissions",
        "permission.selectOrgPermission": "Select Organization Permission",
        "permission.noPermission": "No permission",
        "permission.permissions": "Permissions",
        "permission.noMembersAvailable": "No members available",
        "permission.noMembersDescription":
            "No members can be assigned this permission yet",
        "permission.hasPermission": "Has permission",
        "permission.noPermissionStatus": "No permission",
        "permission.assignPermission": "Assign permission",
        "permission.assigning": "Assigning...",
        "permission.assignSuccess":
            "Successfully assigned permission to member",
        "permission.assignError": "Error occurred while assigning permission",
        "permission.workspaces": "Workspaces",
        "permission.noWorkspaces": "No workspaces",
        "permission.noWorkspacesDescription":
            "No workspaces have been created yet",
        "permission.allWorkspaces": "All workspaces",
        "permission.hasWorkspaceRole": "Has permission",
        "permission.noWorkspaceRole": "No permission",
        "permission.selectWorkspaceFirst":
            "Please select a workspace to assign permission",
        "permission.selectWorkspaceToViewMembers":
            "Select a workspace to view specific members",
        "permission.clickToViewMembers": "Click to view members",
        "permission.availableToAssign": "Available to assign",
        "permission.allMembersHavePermission": "All members have permission",

        // Product
        "product.deals": "Deals",
        "product.variations": "Variations",
        "product.prices": "Prices",
        "product.images": "Images",
        "product.categories": "Categories",
        "product.description": "Description",
        // Confirmations
        "confirm.updateOrgPermission.title": "Update Organization Permission",
        "confirm.updateOrgPermission.description":
            "Are you sure you want to grant '{permissionName}' permission to {name}?",

        // Deals & Customers
        "deal.customers": "Customers",
        "deal.allCustomers": "All customers",
        "deal.sendDetails": "Send details",
        "deal.sendMail": "Send email",
        "deal.saveNote": "Save note",
        "deal.emailSent": "Email sent to customer",
        "deal.totalRevenue": "Total revenue",
        "deal.pipeline": "Pipeline",
        "deal.list": "List",
        "deal.transactions": "Transactions",
        "deal.deleteStage": "Delete stage",
        "deal.loadingMoreDeals": "Loading more deals...",
        "deal.loaded": "Loaded",
        "deal.loadMoreDeals": "Load more deals",
        "deal.dropDealsHere": "Drop deals here",
        "deal.dragToArrangeStages": "Drag to arrange stages",
        "deal.clickToEditName": "Click to edit name",
        "deal.deleteStageConfirm": "Delete this stage?",
        "deal.currentDeals": "Currently: {count} deals in stage {stageName}",
        "deal.whatToDoWithDeals": "What would you like to do with these deals?",
        "deal.moveToOtherStage": "Move to another stage",
        "deal.selectStage": "Select stage",
        "deal.deleteDeals": "Delete deals",
        "deal.cancel": "Cancel",
        "deal.delete": "Delete",
        "deal.confirmDelete": "Are you sure you want to delete this stage?",

        // Customer Timeline
        "customer.addedManually": "Customer added manually",
        "customer.addedFromContacts": "Customer added from contacts",
        "customer.rated": "Customer was rated",
        "customer.revisited": "Customer revisited",
        "customer.firstVisit": "Customer first visit",
        "customer.registered": "Customer registered form",
        "customer.sentMessage": "sent message to customer",

        // Workspace
        "workspace.title": "Workspaces",
        "workspace.noWorkspace":
            "Member has not been assigned to any workspace.",
        "workspace.permissions": "Workspace Permissions",
        "workspace.removeFromWorkspace": "Remove from Workspace",
        "workspace.noOtherPermissions": "No other permissions",
        "workspace.workspace": "Workspace",
        "workspace.selectToAssignRole": "Click to select team permissions",
        "workspace.noAvailableWorkspace": "No workspace available",
        "workspace.selectWorkspace": "Select workspace",
        "workspace.selectWorkspacePlaceholder": "Choose a workspace...",
        "workspace.permissionRequired": "Please select workspace permission",

        // Team
        "team.noTeams": "No sales teams",
        "team.updateRole": "Update Role",
        "team.removeFromTeam": "Remove from Team",
        "team.noOtherRoles": "No other roles",
        "team.teams": "teams",
        "team.hasSubteams": "Has subteams",
        "team.subteam": "Subteam",
        "team.roleRequired": "Please select at least one team role",
        "team.assignTeams": "Assign Teams",

        // Roles
        "role.owner": "Owner",
        "role.admin": "Administrator",
        "role.member": "Member",
        "role.teamLeader": "Team Leader",
        "role.subLeader": "Sub Leader",
        "role.selectRole": "Select role",

        // Actions
        "action.cancel": "Cancel",
        "action.confirm": "Confirm",
        "action.processing": "Processing...",

        // Confirmations
        "confirm.removeFromOrg.title": "Remove Member from Organization",
        "confirm.removeFromOrg.description":
            "Are you sure you want to remove {name} from the organization?",
        "confirm.removeFromTeam.title": "Remove Member from Team",
        "confirm.removeFromTeam.description":
            "Are you sure you want to remove {name} from team {teamName}?",
        "confirm.removeFromWorkspace.title": "Remove Member from Workspace",
        "confirm.removeFromWorkspace.description":
            'Are you sure you want to remove {name} from workspace "{workspaceName}"?',

        // Success messages
        "success.updatedGroupName": "Successfully updated group name",
        "error.updatedGroupName": "An error occurred while updating group name",
        "success.removedFromGroup": "Successfully removed member from group",
        "error.removedFromGroup":
            "An error occurred while removing member from group",
        "success.removedFromOrg":
            "Successfully removed member from organization",
        "success.removedFromTeam":
            "Successfully removed member from team {teamName}",
        "success.removedFromWorkspace":
            "Successfully removed member from workspace",
        "success.grantedPermission":
            'Successfully granted permission "{permissionName}"',
        "success.updatedRole": 'Successfully updated role to "{roleName}"',
        "success.deleteAttachment": "Attachment deleted successfully",
        "success.updateAvatar": "Avatar updated successfully",
        "error.updateAvatar": "An error occurred while updating avatar",
        // Error messages
        "error.deleteAttachment": "An error occurred while deleting attachment",
        "error.removeMember": "An error occurred while removing member",
        "error.removeFromTeam":
            "An error occurred while removing member from team",
        "error.removeFromWorkspace":
            "An error occurred while removing member from workspace",
        "error.grantPermission": "An error occurred while granting permission",
        "error.updateRole": "An error occurred while updating role",
        "error.createCustomer": "An error occurred while creating customer",
        "error.createCustomerDescription":
            "Please check the customer information",
        "success.createCustomer": "Customer created successfully",
        "success.createCustomerDescription":
            "Customer has been created successfully",
        "success.noteCustomer": "Customer note has been saved",
        "error.noteCustomer": "An error occurred while saving customer note",
        "success.updateCustomerStage": "Customer stage updated successfully",
        "error.updateCustomerStage":
            "An error occurred while updating customer stage",
        "success.updateWorkspace": "Workspace updated successfully",
        "error.updateWorkspace": "An error occurred while updating workspace",
        "success.updateStage": "Stage updated successfully",
        "error.updateStage": "An error occurred while updating stage",
        "error.cannotDeleteLastStage": "Cannot delete the last stage!",
        "success.deleteStage": "Stage deleted successfully",
        "error.deleteStage": "An error occurred while deleting stage",
        "success.archiveCustomer": "Customer archived successfully",
        "error.archiveCustomer": "An error occurred while archiving customer",
        "success.archiveRestoreCustomer": "Customer restored successfully",
        "error.archiveRestoreCustomer":
            "An error occurred while restoring customer",
        "common.noArchivedCustomers": "No archived customers",
        "common.archivedCustomers": "Archived customers",
        "success.deleteCustomer": "Customer deleted successfully",
        "error.deleteCustomer": "An error occurred while deleting customer",
        "common.noImage": "No image",

        // Business Process
        "businessProcess.createSuccess":
            "Business process created successfully",
        "businessProcess.createError":
            "An error occurred while creating business process",
        "businessProcess.createTaskSuccess":
            "Business process task created successfully",
        "businessProcess.createTaskError":
            "An error occurred while creating business process task",
        "businessProcess.createNoteSuccess": "Note created successfully",
        "businessProcess.createNoteError":
            "An error occurred while creating note",
        "success.updateTaskStatus": "Update task status successfully",
        "error.updateTaskStatus":
            "An error occurred while updating task status",
        "success.createTag": "Tag created successfully",
        "error.createTag": "An error occurred while creating tag",
        "success.noteLead": "Note saved successfully",
        "error.noteLead": "An error occurred while saving note",
        "success.editNote": "Note updated successfully",
        "error.editNote": "An error occurred while updating note",
        "success.deleteNote": "Note deleted successfully",
        "error.deleteNote": "An error occurred while deleting note",
        "common.uploadAttachmentSuccess": "Attachment uploaded successfully",
        "common.uploadAttachmentFailed":
            "An error occurred while uploading attachment",
        "success.createNote": "Note created successfully",
        "error.createNote": "An error occurred while creating note",
        "success.updateTags": "Successfully updated tags",
        "error.updateTags": "An error occurred while updating tags",
        "success.updateAssignees": "Successfully updated assignees",
        "error.updateAssignees": "An error occurred while updating assignees",
        "success.archieveTask": "Archived successfully",
        "error.archieveTask": "An error occurred while archiving",
        "success.unarchieveTask": "Unarchived successfully",
        "error.unarchiveTask": "An error occurred while unarchiving",
        "success.duplicateTask": "Duplicated successfully",
        "error.duplicateTask": "An error occurred while duplicating",
        "success.deleteTask": "Deleted successfully",
        "error.deleteTask": "An error occurred while deleting",
        "success.updateTask": "Updated successfully",
        "error.updateTask": "An error occurred while updating",
        "error.common": "An error occurred",
        // Nav
        "nav.wallet": "Balance",
        "nav.logout": "Logout",
        "nav.viewProfile": "View Profile",

        // Conversation
        "conversation.linkConversation": "Link conversation",
        "conversation.linkConversationDescription":
            "Are you sure you want to link this conversation?",
        "success.linkConversation": "Conversation linked successfully",
        "error.linkConversation":
            "An error occurred while linking conversation",

        // Leads
        "lead.createLead": "Create new lead",
        "customer.createCustomer": "Create new customer",
        "success.assignLead": "Lead assigned successfully",
        "error.assignLead": "An error occurred while assigning lead",
        "success.updateLead": "Updated successfully",
        "error.updateLead": "An error occurred while updating",
        "success.linkLeadSuccess": "Lead linked successfully",
        "error.linkLeadSuccess": "An error occurred while linking lead",
        "success.linkCustomerSuccess": "Customer linked successfully",
        "error.linkCustomerSuccess": "An error occurred while linking customer",
        "success.unlinkLeadSuccess": "Lead unlinked successfully",
        "error.unlinkLeadSuccess": "An error occurred while unlinking lead",
        "success.unlinkCustomerSuccess": "Customer unlinked successfully",
        "error.unlinkCustomerSuccess":
            "An error occurred while unlinking customer",
        "success.link": "Link successfully",
        "error.link": "An error occurred while linking",
        "success.unlink": "Unlink successfully",
        "error.unlink": "An error occurred while unlinking",
        "nav.automation": "Automation",

        "sucess.update": "Updated successfully",
        "error.update": "An error occurred while updating",
        "success.create": "Created successfully",
        "error.create": "An error occurred while creating",
        "success.delete": "Deleted successfully",
        "error.delete": "An error occurred while deleting",
        "common.extend": "Extend",
        "success.archive": "Archived successfully",
        "common.deleteLead": "Delete Lead",
        "common.addNew": "Add",
        "config.title": "Configuration",
        "config.aichatbot": "AI Chatbot",
        "config.fbconnect": "Facebook Connect",
        "config.form": "Forms",
        "config.zaloconnect": "Zalo Connect",
        "settings.myAccount": "My Account",
        "wallet.title": "Coka Wallet",
        "wallet.deposit": "Deposit",
        "confirm.archive.title": "Confirm Archive",
        "confirm.archive.description":
            "Are you sure you want to archive this deal? The deal will be moved to the archive folder.",
        "confirm.unarchive.title": "Confirm Restore",
        "confirm.unarchive.description":
            "Are you sure you want to restore this deal from the archive?",
        "confirm.duplicate.title": "Confirm Duplicate",
        "confirm.duplicate.description":
            "Are you sure you want to create a copy of this deal?",
        "confirm.delete.title": "Confirm Delete",
        "confirm.delete.description":
            "Are you sure you want to delete this deal? This action cannot be undone.",
        "confirm.unsavedChanges.title": "Confirm Close",
        "confirm.unsavedChanges.description":
            "You have unsaved changes. Are you sure you want to close without saving?",

        // Assign customer
        "success.assignCustomer": "Customer assigned successfully",
        "error.assignCustomer": "An error occurred while assigning customer",
        "common.call": "Call to {phone}",
        "common.settings": "Settings",
        "common.connect": "Connect",
        "common.opportunity": "Opportunity",
        "common.form": "Form",
        "common.aiChatbot": "AI Chatbot",
        "common.followers": "Followers",
        "common.noAssigner": "No assignee",
        "common.assigner": "Owner",
        "common.cancelInvitation": "Cancel Invitation",
        "common.cancelRequest": "Cancel Request",
        "success.cancelInvitation": "Cancel Invitation Success",
        "common.mailBox": "Mail Box",
        "error.cancelInvitation":
            "An error occurred while canceling invitation",
        "success.cancelRequest": "Cancel Request Success",
        "error.cancelRequest": "An error occurred while canceling request",
        "success.acceptInvitation": "Accept Invitation Success",
        "error.acceptInvitation":
            "An error occurred while accepting invitation",
        "success.acceptRequest": "Accept Request Success",
        "error.acceptRequest": "An error occurred while accepting request",
        "success.rejectInvitation": "Reject Invitation Success",
        "error.rejectInvitation":
            "An error occurred while rejecting invitation",
        "success.rejectRequest": "Reject Request Success",
        "error.rejectRequest": "An error occurred while rejecting request",
        "wallet.balance": "Current Balance",
        "error.deleteWorkspace": "An error occurred while deleting workspace",
        "success.deleteWorkspace": "Delete workspace successfully",

        // Member
        "member.searchEmailOrName": "Search by email or name",
        "success.createBusinessProcessTask": "Create deal successfully",
        "error.createBusinessProcessTask":
            "An error occurred while creating deal",
        "success.createWorkspace": "Create workspace successfully",
        "error.createWorkspace": "An error occurred while creating workspace",
        "common.notifications": "Notifications",
        "success.deletedGroup": "Group deleted successfully",
        "error.deletedGroup": "An error occurred while deleting group",
        "common.deleteConfirm":
            "Are you sure you want to delete permission group {name}?",
        "common.eventTransfer": "Event Transfer",
        "common.exportSuccess": "Export successfully",
        "common.exportError": "An error occurred while exporting",
        // Mail-box
        "mail.compose": "Compose",
        "mail.inbox": "Inbox",
        "mail.sent": "Sent",
        "mail.drafts": "Drafts",
        "mail.settings": "Settings",
        "mail.folders": "Folders",
        "mail.labels": "Labels",
        "mail.noLabels": "No labels yet",
        "mail.search": "Search",
        "mail.selectAccount": "Select account",
        "mail.noAccount": "No account",
        "mail.noAccountMessage":
            "No email account configured. Please go to Settings to configure an email account.",
        "mail.reply": "Reply",
        "mail.from": "From",
        "mail.to": "To",
        "mail.cc": "Cc",
        "mail.bcc": "Bcc",
        "mail.subject": "Subject",
        "mail.selectSender": "Select sender",
        "mail.templates": "Templates",
        "mail.insertField": "Insert field",
        "mail.writeWithAI": "Write with AI",
        "mail.send": "Send",
        "mail.sending": "Sending...",
        "mail.saveDraft": "Save draft",
        "mail.savingDraft": "Saving...",
        "mail.sendSuccess": "Email sent successfully!",
        "mail.replySuccess": "Email replied successfully!",
        "mail.sendError": "Cannot send email",
        "mail.draftSaved": "Draft saved successfully!",
        "mail.delete": "Delete",
        "mail.replyAll": "Reply all",
        "mail.forward": "Forward",
        "mail.aiSummary": "AI Summary",
        "mail.addLabel": "Add label",
        "mail.noEmailSelected": "No email selected",
        "mail.selectToRead": "Select an email to read",
        "mail.loading": "Loading...",
        "mail.noEmails": "No emails",
        "mail.loadMore": "Load more",
        "mail.noResultsFound": "No results found",
        "mail.validate.noRecipient": "Please enter recipient",
        "mail.validate.invalidEmail": "Invalid recipient email",
        "mail.validate.invalidCc": "Invalid CC email",
        "mail.validate.invalidBcc": "Invalid BCC email",
        "mail.showMore": "Show more",
        "mail.showLess": "Show less",
        "mail.actions": "Actions",
        "mail.searchPlaceholder": "Search email...",
        "mail.selectAll": "Select all",
        "mail.reload": "Reload",
        "mail.syncing": "Syncing...",
        "mail.loadingMore": "Loading more...",
        "mail.toRecipient": "To",
        "mail.noRecipient": "(No recipient)",
        "mail.conversationsSelected": "conversations selected",
        "mail.bulkActionDescription":
            "You can archive, delete or mark as read for these conversations.",
        "mail.markAsRead": "Mark as read",
        "mail.markAsUnread": "Mark as unread",
        "mail.editDraft": "Edit draft",
        "mail.deleteConfirm": "Delete Email",
        "mail.deleteConfirmSingle":
            "Are you sure you want to move this email to trash?",
        "mail.deleteConfirmBulk":
            "Are you sure you want to move {count} conversations to trash?",
        "mail.deleteConfirmTitle": "Delete this email?",
        "mail.deleteConfirmMessage":
            "Are you sure you want to delete this email? This action cannot be undone.",
        "mail.deleteSuccess": "Email deleted",
        "mail.deleteFailed": "Failed to delete email",

        // Settings & Accounts
        "mail.settings.backToMailbox": "Back to mailbox",
        "mail.settings.title": "Email Accounts Management",
        "mail.settings.description":
            "Add, edit, delete email accounts to connect with the system",
        "mail.settings.addAccount": "Add account",
        "mail.settings.noAccounts": "No email accounts yet",
        "mail.settings.connectPrompt":
            "Connect your email account to send and receive emails directly from the system.",
        "mail.account.displayName": "Display Name",
        "mail.account.displayNamePlaceholder": "Ex: Company Email (John Doe)",
        "mail.account.email": "Email Address",
        "mail.account.emailPlaceholder": "email@example.com",
        "mail.account.username": "Username",
        "mail.account.usernamePlaceholder": "Login Username",
        "mail.account.password": "Password",
        "mail.account.passwordPlaceholder": "App/Email Password",
        "mail.account.passwordHint":
            "Leave empty if you don't want to change password",
        "mail.account.imapHost": "IMAP Host",
        "mail.account.imapPort": "Port",
        "mail.account.smtpServer": "SMTP Server",
        "mail.account.smtpPort": "SMTP Port",
        "mail.account.useSsl": "Use secure connection (SSL/TLS)",
        "mail.account.checkConnection": "Check connection",
        "mail.account.saveSettings": "Save settings",
        "mail.account.updateTitle": "Update Email Account",
        "mail.account.addTitle": "Add New Email Account",
        "mail.account.imapPrompt": "Enter IMAP server information to connect",
        "mail.account.deleteConfirmTitle": "Delete email account",
        "mail.account.deleteConfirmMessage":
            "Are you sure you want to delete this email account? This action cannot be undone.",
        "mail.account.connectionSuccess": "Connection successful!",
        "mail.account.connectionFailed": "Connection failed",
        "mail.account.savedSuccess": "Account settings saved",
        "mail.account.deletedSuccess": "Account deleted",

        // Labels
        "mail.label.create": "Create new label",
        "mail.label.edit": "Edit label",
        "mail.label.name": "Label name",
        "mail.label.color": "Color",
        "mail.label.createButton": "Create label",
        "mail.label.updateButton": "Update label",
        "mail.label.deleteTitle": "Delete label",
        "mail.label.deleteConfirm":
            "Are you sure you want to delete this label?",
        "mail.label.createSuccess": "Label created successfully!",
        "mail.label.updateSuccess": "Label updated successfully",
        "mail.label.deleteSuccess": "Label deleted successfully",

        // Filter
        "mail.filter": "Filter",
        "mail.filter.byDate": "By Date",
        "mail.filter.dateFrom": "Date From",
        "mail.filter.dateTo": "Date To",
        "mail.filter.status": "Status",
        "mail.filter.all": "All",
        "mail.filter.unread": "Unread",
        "mail.filter.read": "Read",
        "mail.filter.attachments": "Attachments",
        "mail.filter.hasAttachments": "Has attachments",
        "mail.filter.noAttachments": "No attachments",
        "mail.filter.classification": "Classification",
        "mail.filter.selected": "selected",
        "mail.filter.selectLabel": "Select label",
        "mail.filter.noLabelsFound": "No labels found",
        "mail.filter.searchSubject": "Search subject",
        "mail.filter.sortBy": "Sort by",
        "mail.filter.dateReceived": "Date received",
        "mail.filter.newest": "Newest",
        "mail.filter.oldest": "Oldest",
        "mail.filter.clear": "Clear filters",
        "mail.apply": "Apply",

        // AI Summary
        "mail.aiSummaryTitle": "AI Summary",
        "mail.analyzing": "Analyzing email...",
        "mail.pleaseWait": "Please wait a moment",
        "mail.summaryContent": "Summary Content",
        "mail.noSummaryData": "No summary data",
        "mail.copiedToClipboard": "Copied to clipboard",

        // Attachments
        "mail.dropFiles": "Drop files here or click to upload",

        // Missing Forward Keys
        "mail.forwardTitle": "Forward Email",
        "mail.additionalMessage": "Additional message",
        "mail.addMessagePlaceholder": "Add your message...",
        "mail.includeAttachments": "Include attachments",
        "mail.cancel": "Cancel",
        "mail.deleteSelected": "Delete selected",
        "mail.loadingDetail": "Loading email details...",
        "mail.noConversationSelected": "No conversation selected",
        "mail.selectConversationPrompt":
            "Select a conversation from the list to view details or take action.",
        "mail.tooltip.editDraft": "Edit draft",
        "mail.tooltip.reply": "Reply to sender",
        "mail.tooltip.replyAll": "Reply all",
        "mail.tooltip.forward": "Forward this email",
        "mail.edit": "Edit",
        "mail.attachment": "Attachment",
        "mail.attachments": "Attachments",
    },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("vi");

    // Load saved language from localStorage
    useEffect(() => {
        const savedLanguage = localStorage.getItem("language") as Language;
        if (
            savedLanguage &&
            (savedLanguage === "vi" || savedLanguage === "en")
        ) {
            setLanguage(savedLanguage);
        }
    }, []);

    // Save language to localStorage when changed
    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("language", lang);
    };

    // Translation function with placeholder support
    const t = (key: string, placeholders?: Record<string, string>): string => {
        let text =
            translations[language][
                key as keyof (typeof translations)[typeof language]
            ] || key;

        // Replace placeholders like {name}, {teamName}, etc.
        if (placeholders) {
            Object.entries(placeholders).forEach(([placeholder, value]) => {
                text = text.replace(new RegExp(`{${placeholder}}`, "g"), value);
            });
        }

        return text;
    };

    return (
        <LanguageContext.Provider
            value={{ language, setLanguage: handleSetLanguage, t }}
        >
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
